### PR TITLE
Add su- prefix content

### PR DESCRIPTION
**Pull request by iamrentman**
# READY FOR REVIEW/NOT READY
Ready

# Summary
Adds The `su-` prefix page content. I thought breaking up the second paragraph and adding the bolds helped the text be easier to scan – happy to change back to exactly what is in the Google doc if you'd like. I also wrapped all the classes in `<code>` elements.

# Needed By (Date)
N/A

# Urgency
Not urgent

# Steps to Test
Go to `/for-developers/strategies-and-conventions/the-su-prefix` and ensure the content matches [the Google doc](https://docs.google.com/document/d/1-HNdgVy0ME1zlXdbmr6O9wzGPDEmoxdta8fUHS_0r-c/edit?usp=sharing).

# Affected Projects or Products
N/A

# Associated Issues and/or People
N/A

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by iamrentman** [comment]
@jdwjdwjdw Curious if you have any idea why this fails?

**Comment by sherakama** [comment]
> 2:24:59 PM: info @next/swc-win32-ia32-msvc@12.1.6: The CPU architecture "x64" is incompatible with this module.

Does somebody have a new computer with a M1 chip?

**Comment by iamrentman** [comment]
Not me. I pushed this commit up and created the PR. I've got a 2019 MacBook with Intel processor. 🤷‍♂️

**Comment by sherakama** [comment]
> 10:51:28 AM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

@jdwjdwjdw Did the build command change? Shouldn't this be building with NPM?

**Comment by sherakama** [comment]
Ah, there is BOTH a package-lock.json and yarn.lock.

Please remove the yarn lock

https://github.com/SU-SWS/decanter-web/blob/feature/su-prefix-content/yarn.lock

**Comment by iamrentman** [comment]
@sherakama @jdwjdwjdw Would you like me to add that (removing the yarn.lock) to this PR? Or a separate PR?

**Review by jdwjdwjdw — APPROVED** [review]
Thanks for taking care of this, @iamrentman and @sherakama! And thanks for the edits to improve how the content looks - I think those changes look great.

**Pull request merged**
