### PR TITLE
ADAPT-5188: Installation Page

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Adds documentation for the installation page

### CODE REVIEW

**Comment by sherakama** [comment]
@jdwjdwjdw 

How does one get code highlighting on their code fences? https://deploy-preview-113--dev-decanter-v7.netlify.app/for-developers/how-to-install

Perhaps: https://dev.to/mikeesto/next-js-mdx-w-code-highlighting-16fi

**Comment by sherakama** [comment]
Also links should have the underline go away on hover/focus to be accessible. "Can't just change color"

**Comment by jdwjdwjdw** [comment]
> @jdwjdwjdw
> 
> How does one get code highlighting on their code fences? https://deploy-preview-113--dev-decanter-v7.netlify.app/for-developers/how-to-install
> 
> Perhaps: https://dev.to/mikeesto/next-js-mdx-w-code-highlighting-16fi

yeah, similar to that. We can install the relevant remark/rehype packages, and then add them to the `contentlayer.config.ts` file. I've got that in-progress work at https://github.com/SU-SWS/decanter-web/pull/114.



> Also links should have the underline go away on hover/focus to be accessible. "Can't just change color"

Do you mind clarifying this? The link behavior here matches our current decanter/stanford sites, but I see what you're saying. But would it be better to have it not underlined by default, and then underlined on hover vs what you are saying (underlined by default, removed on hover)? I don't mind either way, just curious about your preference.

**Comment by sherakama** [comment]
@jdwjdwjdw I'm not sure why or how I edited your last comment but my reply is there anyway.

**Review by jdwjdwjdw — APPROVED** [review]
No worries - it was being weird for me as well. 🤷 

> on our current site the links have the chevron at the end of them and it moves on hover and focus. The buttons change background color and have the underline added on hocus. We need to have something more than just the text color change to be accessible. The underline going away on hocus is fine and easy to implement or you could re-implement the chevron for this site as well.

Thanks for the clarification - I do see the chevron on links that have `su-link--action` applied, but the base `su-link` that you see on most interior pages (e.g. https://decanter.stanford.edu/page/page-about-why-decanter-accessibility/ or https://userguide.sites.stanford.edu/build-and-design) still matches what we've got here. Does that change your opinion on if it needs to be updated? If not, I can plan on making the link updates you mentioned in a separate PR.

Outside of that question, this page looks good to merge!

**Comment by jdwjdwjdw** [comment]
> @jdwjdwjdw
> 
> How does one get code highlighting on their code fences? https://deploy-preview-113--dev-decanter-v7.netlify.app/for-developers/how-to-install
> 
> Perhaps: https://dev.to/mikeesto/next-js-mdx-w-code-highlighting-16fi

My earlier response to this got deleted, but here is was in case you didn't see before:

> yeah, similar to that. We can install the relevant remark/rehype packages, and then add them to the contentlayer.config.ts file. I've got that in-progress work at https://github.com/SU-SWS/decanter-web/pull/114.

**Comment by sherakama** [comment]
> Thanks for the clarification - I do see the chevron on links that have `su-link--action` applied, but the base `su-link` that you see on most interior pages (e.g. [decanter.stanford.edu/page/page-about-why-decanter-accessibility](https://decanter.stanford.edu/page/page-about-why-decanter-accessibility/) or [userguide.sites.stanford.edu/build-and-design](https://userguide.sites.stanford.edu/build-and-design)) still matches what we've got here. Does that change your opinion on if it needs to be updated? If not, I can plan on making the link updates you mentioned in a separate PR.

Yeah, there isn't a `su-link--action` in version 7 so something will have to be done in this site to ensure we are accessible. We already have [had discussions on this](https://stanfordwebservices.slack.com/archives/C2EE9458V/p1625603092097300) on our former site approach.

**Pull request merged**
